//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachmentMessage
    {
        public long MessageAttachmentId { get; set; }
        public long MessageId { get; set; }
        public long PatientId { get; set; }
        public string FileDirectory { get; set; }
        public string FileName { get; set; }
        public string DocumentFormat { get; set; }
        public Nullable<long> UserId_Created { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
