//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillRate
    {
        public BillRate()
        {
            this.BillPayments = new HashSet<BillPayment>();
        }
    
        public int BillRateId { get; set; }
        public string PromoCode { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsFree { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Renewal { get; set; }
        public Nullable<decimal> Residual { get; set; }
        public Nullable<int> FreeMonths { get; set; }
        public Nullable<long> UserId_Created { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> UserId_Modified { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual ICollection<BillPayment> BillPayments { get; set; }
    }
}
