//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillPayment
    {
        public long BillPaymentId { get; set; }
        public long PatientId { get; set; }
        public int BillRateId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Response { get; set; }
        public string CustId { get; set; }
        public string RecurrId { get; set; }
        public string PaymentType { get; set; }
        public string PaymentFrequency { get; set; }
        public string PaymentId { get; set; }
        public Nullable<int> NoOfPayments { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string AccountHolderName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> UserId_Created { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> UserId_Modified { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual BillRate BillRate { get; set; }
    }
}
