//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AuditAction
    {
        public C_AuditAction()
        {
            this.PatientDocumentAudits = new HashSet<PatientDocumentAudit>();
        }
    
        public short AuditActionId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<PatientDocumentAudit> PatientDocumentAudits { get; set; }
    }
}
