//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MaritalStatus
    {
        public C_MaritalStatus()
        {
            this.Patients = new HashSet<Patient>();
        }
    
        public int MaritalStatusId { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
