//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MessageType
    {
        public C_MessageType()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public int MessageTypeId { get; set; }
        public string Value { get; set; }
        public Nullable<bool> General { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
    }
}
