//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Relationship
    {
        public C_Relationship()
        {
            this.PatientEmergencies = new HashSet<PatientEmergency>();
        }
    
        public int RelationshipId { get; set; }
        public string Value { get; set; }
        public string SNOMED { get; set; }
    
        public virtual ICollection<PatientEmergency> PatientEmergencies { get; set; }
    }
}
