//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectReceived
    {
        public long DirectReceivedId { get; set; }
        public Nullable<bool> Processed { get; set; }
        public Nullable<System.DateTime> DateProcessed { get; set; }
        public long PatientId { get; set; }
        public long FacilityId { get; set; }
        public string EmailId { get; set; }
        public string FromEmail { get; set; }
        public string ToEmail { get; set; }
        public string Body { get; set; }
        public string Attachment { get; set; }
        public string Message { get; set; }
    }
}
