//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public Facility()
        {
            this.PatientFacilityLinks = new HashSet<PatientFacilityLink>();
            this.ProviderFacilityLinks = new HashSet<ProviderFacilityLink>();
        }
    
        public long FacilityId { get; set; }
        public Nullable<long> PracticeId { get; set; }
        public Nullable<int> EMRSystemId { get; set; }
        public Nullable<int> FacilityTypeId { get; set; }
        public string FacilityName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string CountryCode { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string BillAddress1 { get; set; }
        public string BillAddress2 { get; set; }
        public string BillAddress3 { get; set; }
        public string BillCity { get; set; }
        public string BillState { get; set; }
        public string BillPostalCode { get; set; }
        public string BillCountryCode { get; set; }
        public string BillPhone { get; set; }
        public string BillFax { get; set; }
        public Nullable<bool> GeneralMessageAvailable { get; set; }
        public Nullable<int> GeneralMessageNotify { get; set; }
        public string GeneralMessageEmail { get; set; }
        public Nullable<bool> AppointmentMessageAvailable { get; set; }
        public Nullable<int> AppointmentMessageNotify { get; set; }
        public string AppointmentMessageEmail { get; set; }
        public Nullable<bool> MedicationMessageAvailable { get; set; }
        public Nullable<int> MedicationMessageNotify { get; set; }
        public string MedicationMessageEmail { get; set; }
        public Nullable<bool> ReferralMessageAvailable { get; set; }
        public Nullable<int> ReferralMessageNotify { get; set; }
        public string ReferralMessageEmail { get; set; }
        public Nullable<bool> PremiumAvailable { get; set; }
        public Nullable<short> OnlineBillPayment { get; set; }
        public Nullable<long> UserId_Created { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> UserId_Modified { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> UserId_Deactivated { get; set; }
        public Nullable<System.DateTime> DateDeactivated { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<PatientFacilityLink> PatientFacilityLinks { get; set; }
        public virtual ICollection<ProviderFacilityLink> ProviderFacilityLinks { get; set; }
        public virtual Practice Practice { get; set; }
    }
}
