//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.MessageAudits = new HashSet<MessageAudit>();
            this.MessageDetails = new HashSet<MessageDetail>();
        }
    
        public long MessageId { get; set; }
        public Nullable<long> PatientId { get; set; }
        public Nullable<int> MessageTypeId { get; set; }
        public Nullable<long> FacilityId { get; set; }
        public Nullable<int> MessageStatusId { get; set; }
        public Nullable<long> UserId_Created { get; set; }
        public string CreatedByName { get; set; }
    
        public virtual C_MessageStatus C_MessageStatus { get; set; }
        public virtual ICollection<MessageAudit> MessageAudits { get; set; }
        public virtual C_MessageType C_MessageType { get; set; }
        public virtual ICollection<MessageDetail> MessageDetails { get; set; }
    }
}
