//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageDetail
    {
        public long MessageId { get; set; }
        public long MessageDetailId { get; set; }
        public Nullable<long> ProviderId_To { get; set; }
        public Nullable<long> ProviderId_From { get; set; }
        public string MessageRequest { get; set; }
        public string MessageResponse { get; set; }
        public Nullable<int> MessageResponseTypeId { get; set; }
        public string PreferredPeriod { get; set; }
        public string PreferredTime { get; set; }
        public string PreferredWeekDay { get; set; }
        public string VisitReason { get; set; }
        public Nullable<bool> MessageUrgency { get; set; }
        public Nullable<System.DateTime> AppointmentStart { get; set; }
        public Nullable<System.DateTime> AppointmentEnd { get; set; }
        public Nullable<long> ProviderId_Appointment { get; set; }
        public string MedicationNDC { get; set; }
        public string MedicationName { get; set; }
        public Nullable<int> NoOfRefills { get; set; }
        public Nullable<int> MedicationStatus { get; set; }
        public string PharmacyName { get; set; }
        public string PharmacyAddress { get; set; }
        public string AttachmentId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> MessageRead { get; set; }
        public string PharmacyPhone { get; set; }
    
        public virtual C_MessageResponseType C_MessageResponseType { get; set; }
        public virtual Message Message { get; set; }
    }
}
