//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientOrgan
    {
        public long PatientId { get; set; }
        public Nullable<bool> Heart { get; set; }
        public Nullable<bool> Liver { get; set; }
        public Nullable<bool> Pancreas { get; set; }
        public Nullable<bool> Lungs { get; set; }
        public Nullable<bool> Kidneys { get; set; }
        public Nullable<bool> Intestines { get; set; }
        public Nullable<bool> Cornea { get; set; }
        public Nullable<bool> Skin { get; set; }
        public Nullable<bool> BoneMarrow { get; set; }
        public Nullable<bool> HeartValves { get; set; }
        public Nullable<bool> ConnectiveTissue { get; set; }
        public Nullable<long> UserId_Created { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> UserId_Modified { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
