//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDocumentAudit
    {
        public long AuditId { get; set; }
        public long PatientId { get; set; }
        public long VisitId { get; set; }
        public long DocCntr { get; set; }
        public long FacilityId { get; set; }
        public Nullable<short> DocumentTypeId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<System.DateTime> TDStamp { get; set; }
        public Nullable<short> AuditActionId { get; set; }
    
        public virtual C_AuditAction C_AuditAction { get; set; }
        public virtual C_DocumentType C_DocumentType { get; set; }
    }
}
