//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientLabResult
    {
        public PatientLabResult()
        {
            this.PatientLabResultTests = new HashSet<PatientLabResultTest>();
        }
    
        public long PatientId { get; set; }
        public long FacilityId { get; set; }
        public long VisitId { get; set; }
        public long LabResultCntr { get; set; }
        public Nullable<long> ProviderId_Requested { get; set; }
        public string CodeValue { get; set; }
        public Nullable<int> CodeSystemId { get; set; }
        public string LabName { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> CollectionDate { get; set; }
        public string Requisiton { get; set; }
        public string Specimen { get; set; }
        public string SpecimenSource { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string Reviewer { get; set; }
        public Nullable<long> UserId_Created { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> UserId_Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
    
        public virtual ICollection<PatientLabResultTest> PatientLabResultTests { get; set; }
    }
}
