//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientClinicalDocument
    {
        public long PatientId { get; set; }
        public long FacilityId { get; set; }
        public long VisitId { get; set; }
        public long DocumentCntr { get; set; }
        public string DocumentDescription { get; set; }
        public string DocumentId { get; set; }
        public string DocumentFormat { get; set; }
        public string StorageLocation { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Viewable { get; set; }
        public Nullable<long> UserId_Created { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> UserId_Modified { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> UserId_Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
    }
}
