//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisit
    {
        public long PatientId { get; set; }
        public long FacilityId { get; set; }
        public long VisitId { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<long> ProviderId { get; set; }
        public string VisitReason { get; set; }
        public Nullable<bool> Viewable { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ClinicalSummary { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> UserId_Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
