//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientRepresentative
    {
        public long UserId { get; set; }
        public long PatientId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> Demographics { get; set; }
        public Nullable<bool> Allergy { get; set; }
        public Nullable<bool> FamilyHistory { get; set; }
        public Nullable<bool> LabResults { get; set; }
        public Nullable<bool> MedicalHistory { get; set; }
        public Nullable<bool> Medication { get; set; }
        public Nullable<bool> Problem { get; set; }
        public Nullable<bool> Procedure { get; set; }
        public Nullable<bool> SocialHistory { get; set; }
        public Nullable<bool> SurgicalHistory { get; set; }
        public Nullable<bool> VitalSigns { get; set; }
        public Nullable<bool> Immunization { get; set; }
        public Nullable<bool> Organ { get; set; }
        public Nullable<bool> ClinicalDoc { get; set; }
        public Nullable<bool> Insurance { get; set; }
        public Nullable<bool> EmergencyContact { get; set; }
        public Nullable<bool> Appointment { get; set; }
        public Nullable<bool> Visit { get; set; }
        public Nullable<bool> UploadDocs { get; set; }
        public Nullable<bool> PlanOfCare { get; set; }
        public Nullable<bool> Messaging { get; set; }
        public Nullable<bool> DownloadTransmit { get; set; }
        public Nullable<bool> ClinicalSummary { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<bool> Provider { get; set; }
    }
}
