//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientWebSetting
    {
        public long PatientId { get; set; }
        public Nullable<short> VisitWidgetLeft { get; set; }
        public Nullable<short> VisitWidgetRight { get; set; }
        public Nullable<short> AllergyWidgetLeft { get; set; }
        public Nullable<short> AllergyWidgetRight { get; set; }
        public Nullable<short> AppointmentsWidgetLeft { get; set; }
        public Nullable<short> AppointmentsWidgetRight { get; set; }
        public Nullable<short> FamilyWidgetLeft { get; set; }
        public Nullable<short> FamilyWidgetRight { get; set; }
        public Nullable<short> ImmunizationWidgetLeft { get; set; }
        public Nullable<short> ImmunizationWidgetRight { get; set; }
        public Nullable<short> InsuranceWidgetLeft { get; set; }
        public Nullable<short> InsuranceWidgetRight { get; set; }
        public Nullable<short> LabTestWidgetLeft { get; set; }
        public Nullable<short> LabTestWidgetRight { get; set; }
        public Nullable<short> MedicationWidgetLeft { get; set; }
        public Nullable<short> MedicationWidgetRight { get; set; }
        public Nullable<short> PastMedicalWidgetLeft { get; set; }
        public Nullable<short> PastMedicalWidgetRight { get; set; }
        public Nullable<short> ProblemWidgetLeft { get; set; }
        public Nullable<short> ProblemWidgetRight { get; set; }
        public Nullable<short> ProcedureWidgetLeft { get; set; }
        public Nullable<short> ProcedureWidgetRight { get; set; }
        public Nullable<short> SocialWidgetLeft { get; set; }
        public Nullable<short> SocialWidgetRight { get; set; }
        public Nullable<short> VitalSignsWidgetLeft { get; set; }
        public Nullable<short> VitalSignsWidgetRight { get; set; }
        public Nullable<short> PremiumWidgetLeft { get; set; }
        public Nullable<short> PremiumWidgetRight { get; set; }
        public Nullable<short> StatementWidgetLeft { get; set; }
        public Nullable<short> StatementWidgetRight { get; set; }
        public Nullable<short> DocumentWidgetLeft { get; set; }
        public Nullable<short> DocumentWidgetRight { get; set; }
        public Nullable<bool> EmailNotifyNewMessage { get; set; }
        public string PictureLocation { get; set; }
        public Nullable<bool> TextNotifyNewMesssage { get; set; }
        public Nullable<int> CellCarrier { get; set; }
        public Nullable<short> PlanOfCareWidgetLeft { get; set; }
        public Nullable<short> PlanOfCareWidgetRight { get; set; }
        public Nullable<short> ClinicalInstructionsWidgetLeft { get; set; }
        public Nullable<short> ClinicalInstructionsWidgetRight { get; set; }
        public Nullable<short> ProviderWidgetLeft { get; set; }
        public Nullable<short> ProviderWidgetRight { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
