//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientFacilityLink
    {
        public long PatientId { get; set; }
        public long FacilityId { get; set; }
        public Nullable<System.DateTime> DataAdded { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Facility Facility { get; set; }
    }
}
