//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVitalSign
    {
        public long PatientId { get; set; }
        public long FacilityId { get; set; }
        public long VisitId { get; set; }
        public long PatientVitalCntr { get; set; }
        public Nullable<System.DateTime> VitalDate { get; set; }
        public Nullable<int> HeightIn { get; set; }
        public Nullable<int> WeightLb { get; set; }
        public string BloodPressurePosn { get; set; }
        public Nullable<int> Systolic { get; set; }
        public Nullable<int> Diastolic { get; set; }
        public Nullable<int> Pulse { get; set; }
        public Nullable<int> Respiration { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public Nullable<long> UserId_Created { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> UserId_Modified { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> UserId_Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
    }
}
