//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientPlanOfCare
    {
        public long PatientId { get; set; }
        public long FacilityId { get; set; }
        public long VisitId { get; set; }
        public long PlanCntr { get; set; }
        public short InstructionTypeId { get; set; }
        public string CodeValue { get; set; }
        public Nullable<int> CodeSystemId { get; set; }
        public string Instruction { get; set; }
        public string Goal { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> AppointmentDateTime { get; set; }
        public Nullable<long> ProviderId { get; set; }
        public Nullable<long> UserId_Created { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> UserId_Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
    
        public virtual C_InstructionType C_InstructionType { get; set; }
    }
}
