//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientLabResultTest
    {
        public long PatientId { get; set; }
        public long FacilityId { get; set; }
        public long VisitId { get; set; }
        public long LabResultCntr { get; set; }
        public int TestCntr { get; set; }
        public string CodeValue { get; set; }
        public Nullable<int> CodeSystemId { get; set; }
        public string Component { get; set; }
        public string Result { get; set; }
        public string RefRange { get; set; }
        public string Units { get; set; }
        public string Abnormal { get; set; }
        public string ResultStatus { get; set; }
    
        public virtual PatientLabResult PatientLabResult { get; set; }
    }
}
