//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMatch
    {
        public long PatientId { get; set; }
        public string FirstClean { get; set; }
        public string LastClean { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string AddressClean { get; set; }
        public string CityClean { get; set; }
        public string StateClean { get; set; }
        public string PostalClean { get; set; }
        public string PhoneClean { get; set; }
        public string FirstSoundex { get; set; }
        public string LastSoundex { get; set; }
    }
}
