//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMedication
    {
        public long PatientId { get; set; }
        public long FacilityId { get; set; }
        public long VisitId { get; set; }
        public long PatientMedicationCntr { get; set; }
        public string CodeValue { get; set; }
        public Nullable<int> CodeSystemId { get; set; }
        public string MedicationName { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string RouteId { get; set; }
        public Nullable<int> Dose { get; set; }
        public string DoseUnit { get; set; }
        public Nullable<int> Refills { get; set; }
        public string Frequency { get; set; }
        public string Sig { get; set; }
        public string Diagnosis { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string Pharmacy { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
        public Nullable<long> UserId_Created { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> UserId_Modified { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> UserId_Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public Nullable<bool> DuringVisit { get; set; }
    }
}
