//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientPolicy
    {
        public long PatientId { get; set; }
        public long PatientPolicyId { get; set; }
        public Nullable<int> PolicyTypeId { get; set; }
        public string PolicyTypeName { get; set; }
        public string Company { get; set; }
        public string PolicyNo { get; set; }
        public string GroupNumber { get; set; }
        public string PlanNumber { get; set; }
        public string Agent { get; set; }
        public string AgentPhone { get; set; }
        public string AgentFax { get; set; }
        public string Notes { get; set; }
        public Nullable<long> UserId_Created { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> UserId_Modified { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> UserId_Deleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
    }
}
