//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.PatientProviderLinks = new HashSet<PatientProviderLink>();
            this.ProviderFacilityLinks = new HashSet<ProviderFacilityLink>();
        }
    
        public long ProviderId { get; set; }
        public long PracticeId { get; set; }
        public long UserId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string DEA { get; set; }
        public string License { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<long> UserId_Created { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> UserId_Modified { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> UserId_Deactivated { get; set; }
        public Nullable<System.DateTime> DateDeactivated { get; set; }
        public string FullName { get; set; }
    
        public virtual ICollection<PatientProviderLink> PatientProviderLinks { get; set; }
        public virtual Practice Practice { get; set; }
        public virtual ICollection<ProviderFacilityLink> ProviderFacilityLinks { get; set; }
    }
}
