//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long UserId { get; set; }
        public string UserLogin { get; set; }
        public string UserEmail { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserRoleId { get; set; }
        public Nullable<long> UserRoleLink { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> LastPasswordChange { get; set; }
        public Nullable<int> FailedLoginCount { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<bool> Locked { get; set; }
        public Nullable<int> SecurityQuestionId { get; set; }
        public string SecurityAnswer { get; set; }
        public Nullable<int> SecurityQuestionId2 { get; set; }
        public string SecurityAnswer2 { get; set; }
        public Nullable<bool> ResetPassword { get; set; }
    
        public virtual C_UserRole C_UserRole { get; set; }
    }
}
