//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCCDAuditLog
    {
        public long AuditId { get; set; }
        public long PatientId { get; set; }
        public string Method { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> TDStamp { get; set; }
    }
}
