//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMessageGetWaiting
    {
        public Nullable<long> FacilityId { get; set; }
        public long MessageId { get; set; }
        public Nullable<long> AMRPatientId { get; set; }
        public Nullable<int> MessageTypeId { get; set; }
        public Nullable<long> ToProvider { get; set; }
        public string MessageRequest { get; set; }
        public Nullable<int> PreferredResponseBy { get; set; }
        public string PreferredPeriod { get; set; }
        public string PreferredTime { get; set; }
        public string PreferredDay { get; set; }
        public string VisitReason { get; set; }
        public Nullable<short> VisitUrgency { get; set; }
        public string Medication { get; set; }
        public string Pharmacy { get; set; }
        public Nullable<System.DateTime> AppointmentStart { get; set; }
        public Nullable<System.DateTime> AppointmentEnd { get; set; }
    }
}
