//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPatientSummary
    {
        public long PatientId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string PAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> HeightFt { get; set; }
        public Nullable<int> HeightIn { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Comments { get; set; }
        public string CountryName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string MobilePhone { get; set; }
        public string EMail { get; set; }
        public string EyeColor { get; set; }
        public string HairColor { get; set; }
        public string OrganDoner { get; set; }
        public Nullable<int> MaritalStatusId { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> PreferredLanguageId { get; set; }
        public string PreferredLanguage { get; set; }
        public Nullable<bool> RaceId_NotAnswer { get; set; }
        public Nullable<bool> RaceId_Native { get; set; }
        public Nullable<bool> RaceId_Asian { get; set; }
        public Nullable<bool> RaceId_Black { get; set; }
        public Nullable<bool> RaceId_Hawaiian { get; set; }
        public Nullable<bool> RaceId_White { get; set; }
        public string Race { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public string Religion { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string Gender { get; set; }
        public Nullable<int> EthnicityId { get; set; }
        public string Ethnicity { get; set; }
        public Nullable<int> BloodTypeId { get; set; }
        public string BloodType { get; set; }
        public Nullable<int> SmokingStatusId { get; set; }
        public string SmokingStatus { get; set; }
        public Nullable<long> PatientEmergencyId { get; set; }
        public Nullable<int> RelationshipId { get; set; }
        public string EmergencyName { get; set; }
        public string EmergencyAddress { get; set; }
        public string EmergencyCity { get; set; }
        public string EmergencyState { get; set; }
        public string EmergencyZip { get; set; }
        public string EmergencyCountryCode { get; set; }
        public string EmergencyCountryName { get; set; }
        public string EmergencyHomePhone { get; set; }
        public string EmergencyMobilePhone { get; set; }
        public string EmergencyWorkPhone { get; set; }
        public Nullable<int> EmergencyRelationshipId { get; set; }
        public string EmergencyRelationship { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public string PCP { get; set; }
        public string MailAddress { get; set; }
        public string MailCity { get; set; }
        public string MailState { get; set; }
        public string MailZip { get; set; }
        public string MailCountryCode { get; set; }
        public string MailCountryName { get; set; }
        public Nullable<bool> Heart { get; set; }
        public Nullable<bool> Liver { get; set; }
        public Nullable<bool> Pancreas { get; set; }
        public Nullable<bool> Lungs { get; set; }
        public Nullable<bool> Kidneys { get; set; }
        public Nullable<bool> Intestines { get; set; }
        public Nullable<bool> Cornea { get; set; }
        public Nullable<bool> Skin { get; set; }
        public Nullable<bool> BoneMarrow { get; set; }
        public Nullable<bool> HeartValves { get; set; }
        public Nullable<bool> ConnectiveTissue { get; set; }
    }
}
