//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRptSecureMessage
    {
        public long MessageDetailId { get; set; }
        public Nullable<long> FacilityId { get; set; }
        public Nullable<long> PatientId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> ProviderId_To { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string License { get; set; }
    }
}
