//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Testing.ISReportService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ReportWSSoap", Namespace="http://tempuri.org/")]
    public partial class ReportWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SecureMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback PatientLoginOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ReportWS() {
            this.Url = global::Testing.Properties.Settings.Default.Testing_ISReportService_ReportWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SecureMessageCompletedEventHandler SecureMessageCompleted;
        
        /// <remarks/>
        public event PatientLoginCompletedEventHandler PatientLoginCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SecureMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SecureMessageResponse SecureMessage(long FacilityId, long UserId, string Token, SecureMessageParms Parms) {
            object[] results = this.Invoke("SecureMessage", new object[] {
                        FacilityId,
                        UserId,
                        Token,
                        Parms});
            return ((SecureMessageResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SecureMessageAsync(long FacilityId, long UserId, string Token, SecureMessageParms Parms) {
            this.SecureMessageAsync(FacilityId, UserId, Token, Parms, null);
        }
        
        /// <remarks/>
        public void SecureMessageAsync(long FacilityId, long UserId, string Token, SecureMessageParms Parms, object userState) {
            if ((this.SecureMessageOperationCompleted == null)) {
                this.SecureMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSecureMessageOperationCompleted);
            }
            this.InvokeAsync("SecureMessage", new object[] {
                        FacilityId,
                        UserId,
                        Token,
                        Parms}, this.SecureMessageOperationCompleted, userState);
        }
        
        private void OnSecureMessageOperationCompleted(object arg) {
            if ((this.SecureMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SecureMessageCompleted(this, new SecureMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PatientLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoginLogResponse PatientLogin(long FacilityId, long UserId, string Token, LoginLogParms Parms) {
            object[] results = this.Invoke("PatientLogin", new object[] {
                        FacilityId,
                        UserId,
                        Token,
                        Parms});
            return ((LoginLogResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PatientLoginAsync(long FacilityId, long UserId, string Token, LoginLogParms Parms) {
            this.PatientLoginAsync(FacilityId, UserId, Token, Parms, null);
        }
        
        /// <remarks/>
        public void PatientLoginAsync(long FacilityId, long UserId, string Token, LoginLogParms Parms, object userState) {
            if ((this.PatientLoginOperationCompleted == null)) {
                this.PatientLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPatientLoginOperationCompleted);
            }
            this.InvokeAsync("PatientLogin", new object[] {
                        FacilityId,
                        UserId,
                        Token,
                        Parms}, this.PatientLoginOperationCompleted, userState);
        }
        
        private void OnPatientLoginOperationCompleted(object arg) {
            if ((this.PatientLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PatientLoginCompleted(this, new PatientLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SecureMessageParms {
        
        private long facilityIdField;
        
        private System.DateTime lastCheckTDField;
        
        /// <remarks/>
        public long FacilityId {
            get {
                return this.facilityIdField;
            }
            set {
                this.facilityIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastCheckTD {
            get {
                return this.lastCheckTDField;
            }
            set {
                this.lastCheckTDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginLogResponse {
        
        private bool validField;
        
        private string errorMessageField;
        
        private System.DateTime lastCheckTDField;
        
        private System.Data.DataTable dtLoginsField;
        
        /// <remarks/>
        public bool Valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastCheckTD {
            get {
                return this.lastCheckTDField;
            }
            set {
                this.lastCheckTDField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable dtLogins {
            get {
                return this.dtLoginsField;
            }
            set {
                this.dtLoginsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginLogParms {
        
        private long facilityIdField;
        
        private System.DateTime lastCheckTDField;
        
        /// <remarks/>
        public long FacilityId {
            get {
                return this.facilityIdField;
            }
            set {
                this.facilityIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastCheckTD {
            get {
                return this.lastCheckTDField;
            }
            set {
                this.lastCheckTDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SecureMessageResponse {
        
        private bool validField;
        
        private string errorMessageField;
        
        private System.DateTime lastCheckTDField;
        
        private System.Data.DataTable dtMessagesField;
        
        /// <remarks/>
        public bool Valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastCheckTD {
            get {
                return this.lastCheckTDField;
            }
            set {
                this.lastCheckTDField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable dtMessages {
            get {
                return this.dtMessagesField;
            }
            set {
                this.dtMessagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SecureMessageCompletedEventHandler(object sender, SecureMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SecureMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SecureMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SecureMessageResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SecureMessageResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PatientLoginCompletedEventHandler(object sender, PatientLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PatientLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PatientLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginLogResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginLogResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591