//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Testing.DirectService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DirectWSSoap", Namespace="http://tempuri.org/")]
    public partial class DirectWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidateEmailAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendDirectEmailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DirectWS() {
            this.Url = global::Testing.Properties.Settings.Default.Testing_DirectService_DirectWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidateEmailAddressCompletedEventHandler ValidateEmailAddressCompleted;
        
        /// <remarks/>
        public event SendDirectEmailCompletedEventHandler SendDirectEmailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateEmailAddress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DirectResponse ValidateEmailAddress(string EmailAddress, string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("ValidateEmailAddress", new object[] {
                        EmailAddress,
                        Token,
                        UserId,
                        FacilityId});
            return ((DirectResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateEmailAddressAsync(string EmailAddress, string Token, long UserId, long FacilityId) {
            this.ValidateEmailAddressAsync(EmailAddress, Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void ValidateEmailAddressAsync(string EmailAddress, string Token, long UserId, long FacilityId, object userState) {
            if ((this.ValidateEmailAddressOperationCompleted == null)) {
                this.ValidateEmailAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateEmailAddressOperationCompleted);
            }
            this.InvokeAsync("ValidateEmailAddress", new object[] {
                        EmailAddress,
                        Token,
                        UserId,
                        FacilityId}, this.ValidateEmailAddressOperationCompleted, userState);
        }
        
        private void OnValidateEmailAddressOperationCompleted(object arg) {
            if ((this.ValidateEmailAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateEmailAddressCompleted(this, new ValidateEmailAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendDirectEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DirectResponse SendDirectEmail(SendDirectParms Parms, string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("SendDirectEmail", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId});
            return ((DirectResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SendDirectEmailAsync(SendDirectParms Parms, string Token, long UserId, long FacilityId) {
            this.SendDirectEmailAsync(Parms, Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void SendDirectEmailAsync(SendDirectParms Parms, string Token, long UserId, long FacilityId, object userState) {
            if ((this.SendDirectEmailOperationCompleted == null)) {
                this.SendDirectEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendDirectEmailOperationCompleted);
            }
            this.InvokeAsync("SendDirectEmail", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId}, this.SendDirectEmailOperationCompleted, userState);
        }
        
        private void OnSendDirectEmailOperationCompleted(object arg) {
            if ((this.SendDirectEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendDirectEmailCompleted(this, new SendDirectEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DirectResponse {
        
        private bool validField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public bool Valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SendDirectParms {
        
        private string emailAddressField;
        
        private long patientIdField;
        
        private long facilityIdField;
        
        private long visitIdField;
        
        private bool problemsField;
        
        private bool allergiesField;
        
        private bool immunizationsField;
        
        private bool medicationsField;
        
        private bool socialField;
        
        private bool proceduresField;
        
        private bool vitalSignsField;
        
        private bool labsField;
        
        private bool clinicalInstructionsField;
        
        private bool futureAppointmentsField;
        
        private bool referralsField;
        
        private bool scheduledTestsField;
        
        private bool decisionAidsField;
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public long PatientId {
            get {
                return this.patientIdField;
            }
            set {
                this.patientIdField = value;
            }
        }
        
        /// <remarks/>
        public long FacilityId {
            get {
                return this.facilityIdField;
            }
            set {
                this.facilityIdField = value;
            }
        }
        
        /// <remarks/>
        public long VisitId {
            get {
                return this.visitIdField;
            }
            set {
                this.visitIdField = value;
            }
        }
        
        /// <remarks/>
        public bool Problems {
            get {
                return this.problemsField;
            }
            set {
                this.problemsField = value;
            }
        }
        
        /// <remarks/>
        public bool Allergies {
            get {
                return this.allergiesField;
            }
            set {
                this.allergiesField = value;
            }
        }
        
        /// <remarks/>
        public bool Immunizations {
            get {
                return this.immunizationsField;
            }
            set {
                this.immunizationsField = value;
            }
        }
        
        /// <remarks/>
        public bool Medications {
            get {
                return this.medicationsField;
            }
            set {
                this.medicationsField = value;
            }
        }
        
        /// <remarks/>
        public bool Social {
            get {
                return this.socialField;
            }
            set {
                this.socialField = value;
            }
        }
        
        /// <remarks/>
        public bool Procedures {
            get {
                return this.proceduresField;
            }
            set {
                this.proceduresField = value;
            }
        }
        
        /// <remarks/>
        public bool VitalSigns {
            get {
                return this.vitalSignsField;
            }
            set {
                this.vitalSignsField = value;
            }
        }
        
        /// <remarks/>
        public bool Labs {
            get {
                return this.labsField;
            }
            set {
                this.labsField = value;
            }
        }
        
        /// <remarks/>
        public bool ClinicalInstructions {
            get {
                return this.clinicalInstructionsField;
            }
            set {
                this.clinicalInstructionsField = value;
            }
        }
        
        /// <remarks/>
        public bool FutureAppointments {
            get {
                return this.futureAppointmentsField;
            }
            set {
                this.futureAppointmentsField = value;
            }
        }
        
        /// <remarks/>
        public bool Referrals {
            get {
                return this.referralsField;
            }
            set {
                this.referralsField = value;
            }
        }
        
        /// <remarks/>
        public bool ScheduledTests {
            get {
                return this.scheduledTestsField;
            }
            set {
                this.scheduledTestsField = value;
            }
        }
        
        /// <remarks/>
        public bool DecisionAids {
            get {
                return this.decisionAidsField;
            }
            set {
                this.decisionAidsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ValidateEmailAddressCompletedEventHandler(object sender, ValidateEmailAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateEmailAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateEmailAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DirectResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DirectResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SendDirectEmailCompletedEventHandler(object sender, SendDirectEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendDirectEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendDirectEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DirectResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DirectResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591