//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace Testing.ISMessageService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MessageWSSoap", Namespace="http://tempuri.org/")]
    public partial class MessageWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MessagePostOperationCompleted;
        
        private System.Threading.SendOrPostCallback NewMessagePostOperationCompleted;
        
        private System.Threading.SendOrPostCallback MessageGetWaitingOperationCompleted;
        
        private System.Threading.SendOrPostCallback MessageGetCancelledOperationCompleted;
        
        private System.Threading.SendOrPostCallback MessagePostReceivedOperationCompleted;
        
        private System.Threading.SendOrPostCallback MessagePostReceivedListOperationCompleted;
        
        private System.Threading.SendOrPostCallback DirectReceivedPostOperationCompleted;
        
        private System.Threading.SendOrPostCallback DirectReceivedGetListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MessageWS() {
            this.Url = global::Testing.Properties.Settings.Default.Testing_MessageService_MessageWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MessagePostCompletedEventHandler MessagePostCompleted;
        
        /// <remarks/>
        public event NewMessagePostCompletedEventHandler NewMessagePostCompleted;
        
        /// <remarks/>
        public event MessageGetWaitingCompletedEventHandler MessageGetWaitingCompleted;
        
        /// <remarks/>
        public event MessageGetCancelledCompletedEventHandler MessageGetCancelledCompleted;
        
        /// <remarks/>
        public event MessagePostReceivedCompletedEventHandler MessagePostReceivedCompleted;
        
        /// <remarks/>
        public event MessagePostReceivedListCompletedEventHandler MessagePostReceivedListCompleted;
        
        /// <remarks/>
        public event DirectReceivedPostCompletedEventHandler DirectReceivedPostCompleted;
        
        /// <remarks/>
        public event DirectReceivedGetListCompletedEventHandler DirectReceivedGetListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MessagePost", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessagePostResult MessagePost(long FacilityId, long UserId, string Token, MessageData MessageData) {
            object[] results = this.Invoke("MessagePost", new object[] {
                        FacilityId,
                        UserId,
                        Token,
                        MessageData});
            return ((MessagePostResult)(results[0]));
        }
        
        /// <remarks/>
        public void MessagePostAsync(long FacilityId, long UserId, string Token, MessageData MessageData) {
            this.MessagePostAsync(FacilityId, UserId, Token, MessageData, null);
        }
        
        /// <remarks/>
        public void MessagePostAsync(long FacilityId, long UserId, string Token, MessageData MessageData, object userState) {
            if ((this.MessagePostOperationCompleted == null)) {
                this.MessagePostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMessagePostOperationCompleted);
            }
            this.InvokeAsync("MessagePost", new object[] {
                        FacilityId,
                        UserId,
                        Token,
                        MessageData}, this.MessagePostOperationCompleted, userState);
        }
        
        private void OnMessagePostOperationCompleted(object arg) {
            if ((this.MessagePostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MessagePostCompleted(this, new MessagePostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NewMessagePost", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessagePostResult NewMessagePost(long FacilityId, long UserId, string Token, NewMessageData MessageData) {
            object[] results = this.Invoke("NewMessagePost", new object[] {
                        FacilityId,
                        UserId,
                        Token,
                        MessageData});
            return ((MessagePostResult)(results[0]));
        }
        
        /// <remarks/>
        public void NewMessagePostAsync(long FacilityId, long UserId, string Token, NewMessageData MessageData) {
            this.NewMessagePostAsync(FacilityId, UserId, Token, MessageData, null);
        }
        
        /// <remarks/>
        public void NewMessagePostAsync(long FacilityId, long UserId, string Token, NewMessageData MessageData, object userState) {
            if ((this.NewMessagePostOperationCompleted == null)) {
                this.NewMessagePostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewMessagePostOperationCompleted);
            }
            this.InvokeAsync("NewMessagePost", new object[] {
                        FacilityId,
                        UserId,
                        Token,
                        MessageData}, this.NewMessagePostOperationCompleted, userState);
        }
        
        private void OnNewMessagePostOperationCompleted(object arg) {
            if ((this.NewMessagePostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NewMessagePostCompleted(this, new NewMessagePostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MessageGetWaiting", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageTableData MessageGetWaiting(long FacilityId, long UserId, string Token) {
            object[] results = this.Invoke("MessageGetWaiting", new object[] {
                        FacilityId,
                        UserId,
                        Token});
            return ((MessageTableData)(results[0]));
        }
        
        /// <remarks/>
        public void MessageGetWaitingAsync(long FacilityId, long UserId, string Token) {
            this.MessageGetWaitingAsync(FacilityId, UserId, Token, null);
        }
        
        /// <remarks/>
        public void MessageGetWaitingAsync(long FacilityId, long UserId, string Token, object userState) {
            if ((this.MessageGetWaitingOperationCompleted == null)) {
                this.MessageGetWaitingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMessageGetWaitingOperationCompleted);
            }
            this.InvokeAsync("MessageGetWaiting", new object[] {
                        FacilityId,
                        UserId,
                        Token}, this.MessageGetWaitingOperationCompleted, userState);
        }
        
        private void OnMessageGetWaitingOperationCompleted(object arg) {
            if ((this.MessageGetWaitingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MessageGetWaitingCompleted(this, new MessageGetWaitingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MessageGetCancelled", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageTableData MessageGetCancelled(long FacilityId, long UserId, string Token) {
            object[] results = this.Invoke("MessageGetCancelled", new object[] {
                        FacilityId,
                        UserId,
                        Token});
            return ((MessageTableData)(results[0]));
        }
        
        /// <remarks/>
        public void MessageGetCancelledAsync(long FacilityId, long UserId, string Token) {
            this.MessageGetCancelledAsync(FacilityId, UserId, Token, null);
        }
        
        /// <remarks/>
        public void MessageGetCancelledAsync(long FacilityId, long UserId, string Token, object userState) {
            if ((this.MessageGetCancelledOperationCompleted == null)) {
                this.MessageGetCancelledOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMessageGetCancelledOperationCompleted);
            }
            this.InvokeAsync("MessageGetCancelled", new object[] {
                        FacilityId,
                        UserId,
                        Token}, this.MessageGetCancelledOperationCompleted, userState);
        }
        
        private void OnMessageGetCancelledOperationCompleted(object arg) {
            if ((this.MessageGetCancelledCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MessageGetCancelledCompleted(this, new MessageGetCancelledCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MessagePostReceived", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessagePostResult MessagePostReceived(long FacilityId, long UserId, string Token, MessageReceived MessageReceived) {
            object[] results = this.Invoke("MessagePostReceived", new object[] {
                        FacilityId,
                        UserId,
                        Token,
                        MessageReceived});
            return ((MessagePostResult)(results[0]));
        }
        
        /// <remarks/>
        public void MessagePostReceivedAsync(long FacilityId, long UserId, string Token, MessageReceived MessageReceived) {
            this.MessagePostReceivedAsync(FacilityId, UserId, Token, MessageReceived, null);
        }
        
        /// <remarks/>
        public void MessagePostReceivedAsync(long FacilityId, long UserId, string Token, MessageReceived MessageReceived, object userState) {
            if ((this.MessagePostReceivedOperationCompleted == null)) {
                this.MessagePostReceivedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMessagePostReceivedOperationCompleted);
            }
            this.InvokeAsync("MessagePostReceived", new object[] {
                        FacilityId,
                        UserId,
                        Token,
                        MessageReceived}, this.MessagePostReceivedOperationCompleted, userState);
        }
        
        private void OnMessagePostReceivedOperationCompleted(object arg) {
            if ((this.MessagePostReceivedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MessagePostReceivedCompleted(this, new MessagePostReceivedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MessagePostReceivedList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessagePostResult MessagePostReceivedList(long FacilityId, long UserId, string Token, string MessageReceivedList) {
            object[] results = this.Invoke("MessagePostReceivedList", new object[] {
                        FacilityId,
                        UserId,
                        Token,
                        MessageReceivedList});
            return ((MessagePostResult)(results[0]));
        }
        
        /// <remarks/>
        public void MessagePostReceivedListAsync(long FacilityId, long UserId, string Token, string MessageReceivedList) {
            this.MessagePostReceivedListAsync(FacilityId, UserId, Token, MessageReceivedList, null);
        }
        
        /// <remarks/>
        public void MessagePostReceivedListAsync(long FacilityId, long UserId, string Token, string MessageReceivedList, object userState) {
            if ((this.MessagePostReceivedListOperationCompleted == null)) {
                this.MessagePostReceivedListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMessagePostReceivedListOperationCompleted);
            }
            this.InvokeAsync("MessagePostReceivedList", new object[] {
                        FacilityId,
                        UserId,
                        Token,
                        MessageReceivedList}, this.MessagePostReceivedListOperationCompleted, userState);
        }
        
        private void OnMessagePostReceivedListOperationCompleted(object arg) {
            if ((this.MessagePostReceivedListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MessagePostReceivedListCompleted(this, new MessagePostReceivedListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DirectReceivedPost", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DirectReceivedResp DirectReceivedPost(long FacilityId, long UserId, string Token, DirectReceivedData DirectData) {
            object[] results = this.Invoke("DirectReceivedPost", new object[] {
                        FacilityId,
                        UserId,
                        Token,
                        DirectData});
            return ((DirectReceivedResp)(results[0]));
        }
        
        /// <remarks/>
        public void DirectReceivedPostAsync(long FacilityId, long UserId, string Token, DirectReceivedData DirectData) {
            this.DirectReceivedPostAsync(FacilityId, UserId, Token, DirectData, null);
        }
        
        /// <remarks/>
        public void DirectReceivedPostAsync(long FacilityId, long UserId, string Token, DirectReceivedData DirectData, object userState) {
            if ((this.DirectReceivedPostOperationCompleted == null)) {
                this.DirectReceivedPostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDirectReceivedPostOperationCompleted);
            }
            this.InvokeAsync("DirectReceivedPost", new object[] {
                        FacilityId,
                        UserId,
                        Token,
                        DirectData}, this.DirectReceivedPostOperationCompleted, userState);
        }
        
        private void OnDirectReceivedPostOperationCompleted(object arg) {
            if ((this.DirectReceivedPostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DirectReceivedPostCompleted(this, new DirectReceivedPostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DirectReceivedGetList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageTableData DirectReceivedGetList(long FacilityId, long UserId, string Token, long FacilityIdSearch, string StartDate, string EndDate) {
            object[] results = this.Invoke("DirectReceivedGetList", new object[] {
                        FacilityId,
                        UserId,
                        Token,
                        FacilityIdSearch,
                        StartDate,
                        EndDate});
            return ((MessageTableData)(results[0]));
        }
        
        /// <remarks/>
        public void DirectReceivedGetListAsync(long FacilityId, long UserId, string Token, long FacilityIdSearch, string StartDate, string EndDate) {
            this.DirectReceivedGetListAsync(FacilityId, UserId, Token, FacilityIdSearch, StartDate, EndDate, null);
        }
        
        /// <remarks/>
        public void DirectReceivedGetListAsync(long FacilityId, long UserId, string Token, long FacilityIdSearch, string StartDate, string EndDate, object userState) {
            if ((this.DirectReceivedGetListOperationCompleted == null)) {
                this.DirectReceivedGetListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDirectReceivedGetListOperationCompleted);
            }
            this.InvokeAsync("DirectReceivedGetList", new object[] {
                        FacilityId,
                        UserId,
                        Token,
                        FacilityIdSearch,
                        StartDate,
                        EndDate}, this.DirectReceivedGetListOperationCompleted, userState);
        }
        
        private void OnDirectReceivedGetListOperationCompleted(object arg) {
            if ((this.DirectReceivedGetListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DirectReceivedGetListCompleted(this, new DirectReceivedGetListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageData {
        
        private long messageIdField;
        
        private long providerIdField;
        
        private string messageResponseField;
        
        private string appointmentStartField;
        
        private string appointmentEndField;
        
        private long appointmentProviderIdField;
        
        private string medicationNDCField;
        
        private string medicationNameField;
        
        private int noOfRefillsField;
        
        private int medicationStatusField;
        
        private string pharmacyNameField;
        
        private string pharmacyAddressField;
        
        private string attachmentNameField;
        
        private string attachmentField;
        
        /// <remarks/>
        public long MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public long ProviderId {
            get {
                return this.providerIdField;
            }
            set {
                this.providerIdField = value;
            }
        }
        
        /// <remarks/>
        public string MessageResponse {
            get {
                return this.messageResponseField;
            }
            set {
                this.messageResponseField = value;
            }
        }
        
        /// <remarks/>
        public string AppointmentStart {
            get {
                return this.appointmentStartField;
            }
            set {
                this.appointmentStartField = value;
            }
        }
        
        /// <remarks/>
        public string AppointmentEnd {
            get {
                return this.appointmentEndField;
            }
            set {
                this.appointmentEndField = value;
            }
        }
        
        /// <remarks/>
        public long AppointmentProviderId {
            get {
                return this.appointmentProviderIdField;
            }
            set {
                this.appointmentProviderIdField = value;
            }
        }
        
        /// <remarks/>
        public string MedicationNDC {
            get {
                return this.medicationNDCField;
            }
            set {
                this.medicationNDCField = value;
            }
        }
        
        /// <remarks/>
        public string MedicationName {
            get {
                return this.medicationNameField;
            }
            set {
                this.medicationNameField = value;
            }
        }
        
        /// <remarks/>
        public int NoOfRefills {
            get {
                return this.noOfRefillsField;
            }
            set {
                this.noOfRefillsField = value;
            }
        }
        
        /// <remarks/>
        public int MedicationStatus {
            get {
                return this.medicationStatusField;
            }
            set {
                this.medicationStatusField = value;
            }
        }
        
        /// <remarks/>
        public string PharmacyName {
            get {
                return this.pharmacyNameField;
            }
            set {
                this.pharmacyNameField = value;
            }
        }
        
        /// <remarks/>
        public string PharmacyAddress {
            get {
                return this.pharmacyAddressField;
            }
            set {
                this.pharmacyAddressField = value;
            }
        }
        
        /// <remarks/>
        public string AttachmentName {
            get {
                return this.attachmentNameField;
            }
            set {
                this.attachmentNameField = value;
            }
        }
        
        /// <remarks/>
        public string Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DirectReceivedResp {
        
        private bool validField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public bool Valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DirectReceivedData {
        
        private long directReceivedIdField;
        
        private bool processedField;
        
        private string dateProcessedField;
        
        private long patientIdField;
        
        private long facilityIdField;
        
        private string emailIdField;
        
        private string fromEmailField;
        
        private string toEmailField;
        
        private string bodyField;
        
        private string attachmentField;
        
        private string messageField;
        
        /// <remarks/>
        public long DirectReceivedId {
            get {
                return this.directReceivedIdField;
            }
            set {
                this.directReceivedIdField = value;
            }
        }
        
        /// <remarks/>
        public bool Processed {
            get {
                return this.processedField;
            }
            set {
                this.processedField = value;
            }
        }
        
        /// <remarks/>
        public string DateProcessed {
            get {
                return this.dateProcessedField;
            }
            set {
                this.dateProcessedField = value;
            }
        }
        
        /// <remarks/>
        public long PatientId {
            get {
                return this.patientIdField;
            }
            set {
                this.patientIdField = value;
            }
        }
        
        /// <remarks/>
        public long FacilityId {
            get {
                return this.facilityIdField;
            }
            set {
                this.facilityIdField = value;
            }
        }
        
        /// <remarks/>
        public string EmailId {
            get {
                return this.emailIdField;
            }
            set {
                this.emailIdField = value;
            }
        }
        
        /// <remarks/>
        public string FromEmail {
            get {
                return this.fromEmailField;
            }
            set {
                this.fromEmailField = value;
            }
        }
        
        /// <remarks/>
        public string ToEmail {
            get {
                return this.toEmailField;
            }
            set {
                this.toEmailField = value;
            }
        }
        
        /// <remarks/>
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        public string Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageReceived {
        
        private System.Data.DataTable dtField;
        
        /// <remarks/>
        public System.Data.DataTable dt {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageTableData {
        
        private bool validField;
        
        private string errorMessageField;
        
        private System.Data.DataTable dtField;
        
        /// <remarks/>
        public bool Valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable dt {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NewMessageData {
        
        private string aMRPatientIdsField;
        
        private long aMRProviderIdField;
        
        private string messageRequestField;
        
        private string attachmentNameField;
        
        private string attachmentField;
        
        /// <remarks/>
        public string AMRPatientIds {
            get {
                return this.aMRPatientIdsField;
            }
            set {
                this.aMRPatientIdsField = value;
            }
        }
        
        /// <remarks/>
        public long AMRProviderId {
            get {
                return this.aMRProviderIdField;
            }
            set {
                this.aMRProviderIdField = value;
            }
        }
        
        /// <remarks/>
        public string MessageRequest {
            get {
                return this.messageRequestField;
            }
            set {
                this.messageRequestField = value;
            }
        }
        
        /// <remarks/>
        public string AttachmentName {
            get {
                return this.attachmentNameField;
            }
            set {
                this.attachmentNameField = value;
            }
        }
        
        /// <remarks/>
        public string Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessagePostResult {
        
        private bool validField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public bool Valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void MessagePostCompletedEventHandler(object sender, MessagePostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MessagePostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MessagePostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessagePostResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessagePostResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void NewMessagePostCompletedEventHandler(object sender, NewMessagePostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewMessagePostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NewMessagePostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessagePostResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessagePostResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void MessageGetWaitingCompletedEventHandler(object sender, MessageGetWaitingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MessageGetWaitingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MessageGetWaitingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageTableData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageTableData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void MessageGetCancelledCompletedEventHandler(object sender, MessageGetCancelledCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MessageGetCancelledCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MessageGetCancelledCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageTableData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageTableData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void MessagePostReceivedCompletedEventHandler(object sender, MessagePostReceivedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MessagePostReceivedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MessagePostReceivedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessagePostResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessagePostResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void MessagePostReceivedListCompletedEventHandler(object sender, MessagePostReceivedListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MessagePostReceivedListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MessagePostReceivedListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessagePostResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessagePostResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void DirectReceivedPostCompletedEventHandler(object sender, DirectReceivedPostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DirectReceivedPostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DirectReceivedPostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DirectReceivedResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DirectReceivedResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void DirectReceivedGetListCompletedEventHandler(object sender, DirectReceivedGetListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DirectReceivedGetListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DirectReceivedGetListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageTableData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageTableData)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591