//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace Testing.MessageService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MessageWSSoap", Namespace="http://tempuri.org/")]
    public partial class MessageWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetMessageDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMessageReadFlagDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveMessageDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageListProviderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageDetailSentListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageDetailReceivedListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageDetailProvSentListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageDetailProvReceivedListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageTypeCodesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageTypeGeneralCodesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageStatusCodesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageResponseTypeCodesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessagePeriodCodesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageAttachmentDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUnreadMessageDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUnreadProvMessageDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendEmailMessageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MessageWS() {
            this.Url = global::Testing.Properties.Settings.Default.Testing_MessageService_MessageWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetMessageDataCompletedEventHandler GetMessageDataCompleted;
        
        /// <remarks/>
        public event UpdateMessageReadFlagDataCompletedEventHandler UpdateMessageReadFlagDataCompleted;
        
        /// <remarks/>
        public event SaveMessageDataCompletedEventHandler SaveMessageDataCompleted;
        
        /// <remarks/>
        public event CancelMessageCompletedEventHandler CancelMessageCompleted;
        
        /// <remarks/>
        public event DeleteMessageCompletedEventHandler DeleteMessageCompleted;
        
        /// <remarks/>
        public event GetMessageListCompletedEventHandler GetMessageListCompleted;
        
        /// <remarks/>
        public event GetMessageListProviderCompletedEventHandler GetMessageListProviderCompleted;
        
        /// <remarks/>
        public event GetMessageDetailSentListCompletedEventHandler GetMessageDetailSentListCompleted;
        
        /// <remarks/>
        public event GetMessageDetailReceivedListCompletedEventHandler GetMessageDetailReceivedListCompleted;
        
        /// <remarks/>
        public event GetMessageDetailProvSentListCompletedEventHandler GetMessageDetailProvSentListCompleted;
        
        /// <remarks/>
        public event GetMessageDetailProvReceivedListCompletedEventHandler GetMessageDetailProvReceivedListCompleted;
        
        /// <remarks/>
        public event GetMessageTypeCodesCompletedEventHandler GetMessageTypeCodesCompleted;
        
        /// <remarks/>
        public event GetMessageTypeGeneralCodesCompletedEventHandler GetMessageTypeGeneralCodesCompleted;
        
        /// <remarks/>
        public event GetMessageStatusCodesCompletedEventHandler GetMessageStatusCodesCompleted;
        
        /// <remarks/>
        public event GetMessageResponseTypeCodesCompletedEventHandler GetMessageResponseTypeCodesCompleted;
        
        /// <remarks/>
        public event GetMessagePeriodCodesCompletedEventHandler GetMessagePeriodCodesCompleted;
        
        /// <remarks/>
        public event GetMessageAttachmentDataCompletedEventHandler GetMessageAttachmentDataCompleted;
        
        /// <remarks/>
        public event GetUnreadMessageDataCompletedEventHandler GetUnreadMessageDataCompleted;
        
        /// <remarks/>
        public event GetUnreadProvMessageDataCompletedEventHandler GetUnreadProvMessageDataCompleted;
        
        /// <remarks/>
        public event SendEmailMessageCompletedEventHandler SendEmailMessageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessageData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageData GetMessageData(MessageParms Parms, string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("GetMessageData", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId});
            return ((MessageData)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageDataAsync(MessageParms Parms, string Token, long UserId, long FacilityId) {
            this.GetMessageDataAsync(Parms, Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void GetMessageDataAsync(MessageParms Parms, string Token, long UserId, long FacilityId, object userState) {
            if ((this.GetMessageDataOperationCompleted == null)) {
                this.GetMessageDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageDataOperationCompleted);
            }
            this.InvokeAsync("GetMessageData", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId}, this.GetMessageDataOperationCompleted, userState);
        }
        
        private void OnGetMessageDataOperationCompleted(object arg) {
            if ((this.GetMessageDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageDataCompleted(this, new GetMessageDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateMessageReadFlagData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageData UpdateMessageReadFlagData(MessageData MessageData, string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("UpdateMessageReadFlagData", new object[] {
                        MessageData,
                        Token,
                        UserId,
                        FacilityId});
            return ((MessageData)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMessageReadFlagDataAsync(MessageData MessageData, string Token, long UserId, long FacilityId) {
            this.UpdateMessageReadFlagDataAsync(MessageData, Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void UpdateMessageReadFlagDataAsync(MessageData MessageData, string Token, long UserId, long FacilityId, object userState) {
            if ((this.UpdateMessageReadFlagDataOperationCompleted == null)) {
                this.UpdateMessageReadFlagDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMessageReadFlagDataOperationCompleted);
            }
            this.InvokeAsync("UpdateMessageReadFlagData", new object[] {
                        MessageData,
                        Token,
                        UserId,
                        FacilityId}, this.UpdateMessageReadFlagDataOperationCompleted, userState);
        }
        
        private void OnUpdateMessageReadFlagDataOperationCompleted(object arg) {
            if ((this.UpdateMessageReadFlagDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMessageReadFlagDataCompleted(this, new UpdateMessageReadFlagDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveMessageData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageData SaveMessageData(MessageData MessageData, string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("SaveMessageData", new object[] {
                        MessageData,
                        Token,
                        UserId,
                        FacilityId});
            return ((MessageData)(results[0]));
        }
        
        /// <remarks/>
        public void SaveMessageDataAsync(MessageData MessageData, string Token, long UserId, long FacilityId) {
            this.SaveMessageDataAsync(MessageData, Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void SaveMessageDataAsync(MessageData MessageData, string Token, long UserId, long FacilityId, object userState) {
            if ((this.SaveMessageDataOperationCompleted == null)) {
                this.SaveMessageDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveMessageDataOperationCompleted);
            }
            this.InvokeAsync("SaveMessageData", new object[] {
                        MessageData,
                        Token,
                        UserId,
                        FacilityId}, this.SaveMessageDataOperationCompleted, userState);
        }
        
        private void OnSaveMessageDataOperationCompleted(object arg) {
            if ((this.SaveMessageDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveMessageDataCompleted(this, new SaveMessageDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageData CancelMessage(MessageData MessageData, string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("CancelMessage", new object[] {
                        MessageData,
                        Token,
                        UserId,
                        FacilityId});
            return ((MessageData)(results[0]));
        }
        
        /// <remarks/>
        public void CancelMessageAsync(MessageData MessageData, string Token, long UserId, long FacilityId) {
            this.CancelMessageAsync(MessageData, Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void CancelMessageAsync(MessageData MessageData, string Token, long UserId, long FacilityId, object userState) {
            if ((this.CancelMessageOperationCompleted == null)) {
                this.CancelMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelMessageOperationCompleted);
            }
            this.InvokeAsync("CancelMessage", new object[] {
                        MessageData,
                        Token,
                        UserId,
                        FacilityId}, this.CancelMessageOperationCompleted, userState);
        }
        
        private void OnCancelMessageOperationCompleted(object arg) {
            if ((this.CancelMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelMessageCompleted(this, new CancelMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageData DeleteMessage(MessageData MessageData, string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("DeleteMessage", new object[] {
                        MessageData,
                        Token,
                        UserId,
                        FacilityId});
            return ((MessageData)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteMessageAsync(MessageData MessageData, string Token, long UserId, long FacilityId) {
            this.DeleteMessageAsync(MessageData, Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void DeleteMessageAsync(MessageData MessageData, string Token, long UserId, long FacilityId, object userState) {
            if ((this.DeleteMessageOperationCompleted == null)) {
                this.DeleteMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMessageOperationCompleted);
            }
            this.InvokeAsync("DeleteMessage", new object[] {
                        MessageData,
                        Token,
                        UserId,
                        FacilityId}, this.DeleteMessageOperationCompleted, userState);
        }
        
        private void OnDeleteMessageOperationCompleted(object arg) {
            if ((this.DeleteMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMessageCompleted(this, new DeleteMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessageList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageTableData GetMessageList(MessageParms Parms, string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("GetMessageList", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId});
            return ((MessageTableData)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageListAsync(MessageParms Parms, string Token, long UserId, long FacilityId) {
            this.GetMessageListAsync(Parms, Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void GetMessageListAsync(MessageParms Parms, string Token, long UserId, long FacilityId, object userState) {
            if ((this.GetMessageListOperationCompleted == null)) {
                this.GetMessageListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageListOperationCompleted);
            }
            this.InvokeAsync("GetMessageList", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId}, this.GetMessageListOperationCompleted, userState);
        }
        
        private void OnGetMessageListOperationCompleted(object arg) {
            if ((this.GetMessageListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageListCompleted(this, new GetMessageListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessageListProvider", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageTableData GetMessageListProvider(MessageParms Parms, string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("GetMessageListProvider", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId});
            return ((MessageTableData)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageListProviderAsync(MessageParms Parms, string Token, long UserId, long FacilityId) {
            this.GetMessageListProviderAsync(Parms, Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void GetMessageListProviderAsync(MessageParms Parms, string Token, long UserId, long FacilityId, object userState) {
            if ((this.GetMessageListProviderOperationCompleted == null)) {
                this.GetMessageListProviderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageListProviderOperationCompleted);
            }
            this.InvokeAsync("GetMessageListProvider", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId}, this.GetMessageListProviderOperationCompleted, userState);
        }
        
        private void OnGetMessageListProviderOperationCompleted(object arg) {
            if ((this.GetMessageListProviderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageListProviderCompleted(this, new GetMessageListProviderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessageDetailSentList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageTableData GetMessageDetailSentList(MessageParms Parms, string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("GetMessageDetailSentList", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId});
            return ((MessageTableData)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageDetailSentListAsync(MessageParms Parms, string Token, long UserId, long FacilityId) {
            this.GetMessageDetailSentListAsync(Parms, Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void GetMessageDetailSentListAsync(MessageParms Parms, string Token, long UserId, long FacilityId, object userState) {
            if ((this.GetMessageDetailSentListOperationCompleted == null)) {
                this.GetMessageDetailSentListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageDetailSentListOperationCompleted);
            }
            this.InvokeAsync("GetMessageDetailSentList", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId}, this.GetMessageDetailSentListOperationCompleted, userState);
        }
        
        private void OnGetMessageDetailSentListOperationCompleted(object arg) {
            if ((this.GetMessageDetailSentListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageDetailSentListCompleted(this, new GetMessageDetailSentListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessageDetailReceivedList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageTableData GetMessageDetailReceivedList(MessageParms Parms, string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("GetMessageDetailReceivedList", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId});
            return ((MessageTableData)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageDetailReceivedListAsync(MessageParms Parms, string Token, long UserId, long FacilityId) {
            this.GetMessageDetailReceivedListAsync(Parms, Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void GetMessageDetailReceivedListAsync(MessageParms Parms, string Token, long UserId, long FacilityId, object userState) {
            if ((this.GetMessageDetailReceivedListOperationCompleted == null)) {
                this.GetMessageDetailReceivedListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageDetailReceivedListOperationCompleted);
            }
            this.InvokeAsync("GetMessageDetailReceivedList", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId}, this.GetMessageDetailReceivedListOperationCompleted, userState);
        }
        
        private void OnGetMessageDetailReceivedListOperationCompleted(object arg) {
            if ((this.GetMessageDetailReceivedListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageDetailReceivedListCompleted(this, new GetMessageDetailReceivedListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessageDetailProvSentList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageTableData GetMessageDetailProvSentList(MessageParms Parms, string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("GetMessageDetailProvSentList", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId});
            return ((MessageTableData)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageDetailProvSentListAsync(MessageParms Parms, string Token, long UserId, long FacilityId) {
            this.GetMessageDetailProvSentListAsync(Parms, Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void GetMessageDetailProvSentListAsync(MessageParms Parms, string Token, long UserId, long FacilityId, object userState) {
            if ((this.GetMessageDetailProvSentListOperationCompleted == null)) {
                this.GetMessageDetailProvSentListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageDetailProvSentListOperationCompleted);
            }
            this.InvokeAsync("GetMessageDetailProvSentList", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId}, this.GetMessageDetailProvSentListOperationCompleted, userState);
        }
        
        private void OnGetMessageDetailProvSentListOperationCompleted(object arg) {
            if ((this.GetMessageDetailProvSentListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageDetailProvSentListCompleted(this, new GetMessageDetailProvSentListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessageDetailProvReceivedList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageTableData GetMessageDetailProvReceivedList(MessageParms Parms, string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("GetMessageDetailProvReceivedList", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId});
            return ((MessageTableData)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageDetailProvReceivedListAsync(MessageParms Parms, string Token, long UserId, long FacilityId) {
            this.GetMessageDetailProvReceivedListAsync(Parms, Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void GetMessageDetailProvReceivedListAsync(MessageParms Parms, string Token, long UserId, long FacilityId, object userState) {
            if ((this.GetMessageDetailProvReceivedListOperationCompleted == null)) {
                this.GetMessageDetailProvReceivedListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageDetailProvReceivedListOperationCompleted);
            }
            this.InvokeAsync("GetMessageDetailProvReceivedList", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId}, this.GetMessageDetailProvReceivedListOperationCompleted, userState);
        }
        
        private void OnGetMessageDetailProvReceivedListOperationCompleted(object arg) {
            if ((this.GetMessageDetailProvReceivedListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageDetailProvReceivedListCompleted(this, new GetMessageDetailProvReceivedListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessageTypeCodes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CodeTableData GetMessageTypeCodes(string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("GetMessageTypeCodes", new object[] {
                        Token,
                        UserId,
                        FacilityId});
            return ((CodeTableData)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageTypeCodesAsync(string Token, long UserId, long FacilityId) {
            this.GetMessageTypeCodesAsync(Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void GetMessageTypeCodesAsync(string Token, long UserId, long FacilityId, object userState) {
            if ((this.GetMessageTypeCodesOperationCompleted == null)) {
                this.GetMessageTypeCodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageTypeCodesOperationCompleted);
            }
            this.InvokeAsync("GetMessageTypeCodes", new object[] {
                        Token,
                        UserId,
                        FacilityId}, this.GetMessageTypeCodesOperationCompleted, userState);
        }
        
        private void OnGetMessageTypeCodesOperationCompleted(object arg) {
            if ((this.GetMessageTypeCodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageTypeCodesCompleted(this, new GetMessageTypeCodesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessageTypeGeneralCodes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CodeTableData GetMessageTypeGeneralCodes(string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("GetMessageTypeGeneralCodes", new object[] {
                        Token,
                        UserId,
                        FacilityId});
            return ((CodeTableData)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageTypeGeneralCodesAsync(string Token, long UserId, long FacilityId) {
            this.GetMessageTypeGeneralCodesAsync(Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void GetMessageTypeGeneralCodesAsync(string Token, long UserId, long FacilityId, object userState) {
            if ((this.GetMessageTypeGeneralCodesOperationCompleted == null)) {
                this.GetMessageTypeGeneralCodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageTypeGeneralCodesOperationCompleted);
            }
            this.InvokeAsync("GetMessageTypeGeneralCodes", new object[] {
                        Token,
                        UserId,
                        FacilityId}, this.GetMessageTypeGeneralCodesOperationCompleted, userState);
        }
        
        private void OnGetMessageTypeGeneralCodesOperationCompleted(object arg) {
            if ((this.GetMessageTypeGeneralCodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageTypeGeneralCodesCompleted(this, new GetMessageTypeGeneralCodesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessageStatusCodes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CodeTableData GetMessageStatusCodes(string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("GetMessageStatusCodes", new object[] {
                        Token,
                        UserId,
                        FacilityId});
            return ((CodeTableData)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageStatusCodesAsync(string Token, long UserId, long FacilityId) {
            this.GetMessageStatusCodesAsync(Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void GetMessageStatusCodesAsync(string Token, long UserId, long FacilityId, object userState) {
            if ((this.GetMessageStatusCodesOperationCompleted == null)) {
                this.GetMessageStatusCodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageStatusCodesOperationCompleted);
            }
            this.InvokeAsync("GetMessageStatusCodes", new object[] {
                        Token,
                        UserId,
                        FacilityId}, this.GetMessageStatusCodesOperationCompleted, userState);
        }
        
        private void OnGetMessageStatusCodesOperationCompleted(object arg) {
            if ((this.GetMessageStatusCodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageStatusCodesCompleted(this, new GetMessageStatusCodesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessageResponseTypeCodes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CodeTableData GetMessageResponseTypeCodes(string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("GetMessageResponseTypeCodes", new object[] {
                        Token,
                        UserId,
                        FacilityId});
            return ((CodeTableData)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageResponseTypeCodesAsync(string Token, long UserId, long FacilityId) {
            this.GetMessageResponseTypeCodesAsync(Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void GetMessageResponseTypeCodesAsync(string Token, long UserId, long FacilityId, object userState) {
            if ((this.GetMessageResponseTypeCodesOperationCompleted == null)) {
                this.GetMessageResponseTypeCodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageResponseTypeCodesOperationCompleted);
            }
            this.InvokeAsync("GetMessageResponseTypeCodes", new object[] {
                        Token,
                        UserId,
                        FacilityId}, this.GetMessageResponseTypeCodesOperationCompleted, userState);
        }
        
        private void OnGetMessageResponseTypeCodesOperationCompleted(object arg) {
            if ((this.GetMessageResponseTypeCodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageResponseTypeCodesCompleted(this, new GetMessageResponseTypeCodesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessagePeriodCodes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CodeTableData GetMessagePeriodCodes(string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("GetMessagePeriodCodes", new object[] {
                        Token,
                        UserId,
                        FacilityId});
            return ((CodeTableData)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessagePeriodCodesAsync(string Token, long UserId, long FacilityId) {
            this.GetMessagePeriodCodesAsync(Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void GetMessagePeriodCodesAsync(string Token, long UserId, long FacilityId, object userState) {
            if ((this.GetMessagePeriodCodesOperationCompleted == null)) {
                this.GetMessagePeriodCodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessagePeriodCodesOperationCompleted);
            }
            this.InvokeAsync("GetMessagePeriodCodes", new object[] {
                        Token,
                        UserId,
                        FacilityId}, this.GetMessagePeriodCodesOperationCompleted, userState);
        }
        
        private void OnGetMessagePeriodCodesOperationCompleted(object arg) {
            if ((this.GetMessagePeriodCodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessagePeriodCodesCompleted(this, new GetMessagePeriodCodesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessageAttachmentData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageAttachmentData GetMessageAttachmentData(MessageAttachmentData Parms, string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("GetMessageAttachmentData", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId});
            return ((MessageAttachmentData)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageAttachmentDataAsync(MessageAttachmentData Parms, string Token, long UserId, long FacilityId) {
            this.GetMessageAttachmentDataAsync(Parms, Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void GetMessageAttachmentDataAsync(MessageAttachmentData Parms, string Token, long UserId, long FacilityId, object userState) {
            if ((this.GetMessageAttachmentDataOperationCompleted == null)) {
                this.GetMessageAttachmentDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageAttachmentDataOperationCompleted);
            }
            this.InvokeAsync("GetMessageAttachmentData", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId}, this.GetMessageAttachmentDataOperationCompleted, userState);
        }
        
        private void OnGetMessageAttachmentDataOperationCompleted(object arg) {
            if ((this.GetMessageAttachmentDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageAttachmentDataCompleted(this, new GetMessageAttachmentDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUnreadMessageData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageUnread GetUnreadMessageData(MessageParms Parms, string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("GetUnreadMessageData", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId});
            return ((MessageUnread)(results[0]));
        }
        
        /// <remarks/>
        public void GetUnreadMessageDataAsync(MessageParms Parms, string Token, long UserId, long FacilityId) {
            this.GetUnreadMessageDataAsync(Parms, Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void GetUnreadMessageDataAsync(MessageParms Parms, string Token, long UserId, long FacilityId, object userState) {
            if ((this.GetUnreadMessageDataOperationCompleted == null)) {
                this.GetUnreadMessageDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUnreadMessageDataOperationCompleted);
            }
            this.InvokeAsync("GetUnreadMessageData", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId}, this.GetUnreadMessageDataOperationCompleted, userState);
        }
        
        private void OnGetUnreadMessageDataOperationCompleted(object arg) {
            if ((this.GetUnreadMessageDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUnreadMessageDataCompleted(this, new GetUnreadMessageDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUnreadProvMessageData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessageUnread GetUnreadProvMessageData(MessageParms Parms, string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("GetUnreadProvMessageData", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId});
            return ((MessageUnread)(results[0]));
        }
        
        /// <remarks/>
        public void GetUnreadProvMessageDataAsync(MessageParms Parms, string Token, long UserId, long FacilityId) {
            this.GetUnreadProvMessageDataAsync(Parms, Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void GetUnreadProvMessageDataAsync(MessageParms Parms, string Token, long UserId, long FacilityId, object userState) {
            if ((this.GetUnreadProvMessageDataOperationCompleted == null)) {
                this.GetUnreadProvMessageDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUnreadProvMessageDataOperationCompleted);
            }
            this.InvokeAsync("GetUnreadProvMessageData", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId}, this.GetUnreadProvMessageDataOperationCompleted, userState);
        }
        
        private void OnGetUnreadProvMessageDataOperationCompleted(object arg) {
            if ((this.GetUnreadProvMessageDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUnreadProvMessageDataCompleted(this, new GetUnreadProvMessageDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmailMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmailMessageData SendEmailMessage(EmailMessageData Parms, string Token, long UserId, long FacilityId) {
            object[] results = this.Invoke("SendEmailMessage", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId});
            return ((EmailMessageData)(results[0]));
        }
        
        /// <remarks/>
        public void SendEmailMessageAsync(EmailMessageData Parms, string Token, long UserId, long FacilityId) {
            this.SendEmailMessageAsync(Parms, Token, UserId, FacilityId, null);
        }
        
        /// <remarks/>
        public void SendEmailMessageAsync(EmailMessageData Parms, string Token, long UserId, long FacilityId, object userState) {
            if ((this.SendEmailMessageOperationCompleted == null)) {
                this.SendEmailMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailMessageOperationCompleted);
            }
            this.InvokeAsync("SendEmailMessage", new object[] {
                        Parms,
                        Token,
                        UserId,
                        FacilityId}, this.SendEmailMessageOperationCompleted, userState);
        }
        
        private void OnSendEmailMessageOperationCompleted(object arg) {
            if ((this.SendEmailMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailMessageCompleted(this, new SendEmailMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageParms {
        
        private int optionField;
        
        private long messageIdField;
        
        private long patientIdField;
        
        private long providerIdField;
        
        /// <remarks/>
        public int Option {
            get {
                return this.optionField;
            }
            set {
                this.optionField = value;
            }
        }
        
        /// <remarks/>
        public long MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public long PatientId {
            get {
                return this.patientIdField;
            }
            set {
                this.patientIdField = value;
            }
        }
        
        /// <remarks/>
        public long ProviderId {
            get {
                return this.providerIdField;
            }
            set {
                this.providerIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EmailMessageData {
        
        private bool validField;
        
        private string errorMessageField;
        
        private string toField;
        
        private string subjectField;
        
        private string bodyField;
        
        /// <remarks/>
        public bool Valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageUnread {
        
        private bool validField;
        
        private string errorMessageField;
        
        private int totalMessagesField;
        
        private int appointmentMessagesField;
        
        private int medicationMessagesField;
        
        private int referralMessagesField;
        
        private int generalMessagesField;
        
        /// <remarks/>
        public bool Valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public int TotalMessages {
            get {
                return this.totalMessagesField;
            }
            set {
                this.totalMessagesField = value;
            }
        }
        
        /// <remarks/>
        public int AppointmentMessages {
            get {
                return this.appointmentMessagesField;
            }
            set {
                this.appointmentMessagesField = value;
            }
        }
        
        /// <remarks/>
        public int MedicationMessages {
            get {
                return this.medicationMessagesField;
            }
            set {
                this.medicationMessagesField = value;
            }
        }
        
        /// <remarks/>
        public int ReferralMessages {
            get {
                return this.referralMessagesField;
            }
            set {
                this.referralMessagesField = value;
            }
        }
        
        /// <remarks/>
        public int GeneralMessages {
            get {
                return this.generalMessagesField;
            }
            set {
                this.generalMessagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageAttachmentData {
        
        private bool validField;
        
        private string errorMessageField;
        
        private long messageAttachmentIdField;
        
        private long messageIdField;
        
        private long patientIdField;
        
        private string fileDirectoryField;
        
        private string fileNameField;
        
        private string documentFormatField;
        
        private byte[] documentImageField;
        
        /// <remarks/>
        public bool Valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public long MessageAttachmentId {
            get {
                return this.messageAttachmentIdField;
            }
            set {
                this.messageAttachmentIdField = value;
            }
        }
        
        /// <remarks/>
        public long MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public long PatientId {
            get {
                return this.patientIdField;
            }
            set {
                this.patientIdField = value;
            }
        }
        
        /// <remarks/>
        public string FileDirectory {
            get {
                return this.fileDirectoryField;
            }
            set {
                this.fileDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentFormat {
            get {
                return this.documentFormatField;
            }
            set {
                this.documentFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DocumentImage {
            get {
                return this.documentImageField;
            }
            set {
                this.documentImageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CodeTableData {
        
        private bool validField;
        
        private string errorMessageField;
        
        private System.Data.DataTable dtField;
        
        /// <remarks/>
        public bool Valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable dt {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageTableData {
        
        private bool validField;
        
        private string errorMessageField;
        
        private System.Data.DataTable dtField;
        
        /// <remarks/>
        public bool Valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable dt {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageData {
        
        private bool validField;
        
        private string errorMessageField;
        
        private long messageIdField;
        
        private long patientIdField;
        
        private int messageTypeIdField;
        
        private long facilityIdField;
        
        private int messageStatusIdField;
        
        private long user_Id_CreatedField;
        
        private string createdByNameField;
        
        private long messageDetailIdField;
        
        private System.Nullable<long> providerId_ToField;
        
        private System.Nullable<long> providerId_FromField;
        
        private string messageRequestField;
        
        private string messageResponseField;
        
        private int messageResponseTypeIdField;
        
        private string preferredPeriodField;
        
        private string preferredTimeField;
        
        private string preferredWeekDayField;
        
        private string visitReasonField;
        
        private bool messageUrgencyField;
        
        private System.DateTime appointmentStartField;
        
        private System.DateTime appointmentEndField;
        
        private long providerId_AppointmentField;
        
        private string medicationNDCField;
        
        private string medicationNameField;
        
        private int noOfRefillsField;
        
        private int medicationStatusField;
        
        private string pharmacyNameField;
        
        private string pharmacyAddressField;
        
        private string pharmacyPhoneField;
        
        private bool messageReadField;
        
        private string attachmentIdField;
        
        private string attachmentNameField;
        
        private byte[] attachmentField;
        
        private System.Data.DataTable dtDetailsField;
        
        /// <remarks/>
        public bool Valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public long MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public long PatientId {
            get {
                return this.patientIdField;
            }
            set {
                this.patientIdField = value;
            }
        }
        
        /// <remarks/>
        public int MessageTypeId {
            get {
                return this.messageTypeIdField;
            }
            set {
                this.messageTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public long FacilityId {
            get {
                return this.facilityIdField;
            }
            set {
                this.facilityIdField = value;
            }
        }
        
        /// <remarks/>
        public int MessageStatusId {
            get {
                return this.messageStatusIdField;
            }
            set {
                this.messageStatusIdField = value;
            }
        }
        
        /// <remarks/>
        public long User_Id_Created {
            get {
                return this.user_Id_CreatedField;
            }
            set {
                this.user_Id_CreatedField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedByName {
            get {
                return this.createdByNameField;
            }
            set {
                this.createdByNameField = value;
            }
        }
        
        /// <remarks/>
        public long MessageDetailId {
            get {
                return this.messageDetailIdField;
            }
            set {
                this.messageDetailIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> ProviderId_To {
            get {
                return this.providerId_ToField;
            }
            set {
                this.providerId_ToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> ProviderId_From {
            get {
                return this.providerId_FromField;
            }
            set {
                this.providerId_FromField = value;
            }
        }
        
        /// <remarks/>
        public string MessageRequest {
            get {
                return this.messageRequestField;
            }
            set {
                this.messageRequestField = value;
            }
        }
        
        /// <remarks/>
        public string MessageResponse {
            get {
                return this.messageResponseField;
            }
            set {
                this.messageResponseField = value;
            }
        }
        
        /// <remarks/>
        public int MessageResponseTypeId {
            get {
                return this.messageResponseTypeIdField;
            }
            set {
                this.messageResponseTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public string PreferredPeriod {
            get {
                return this.preferredPeriodField;
            }
            set {
                this.preferredPeriodField = value;
            }
        }
        
        /// <remarks/>
        public string PreferredTime {
            get {
                return this.preferredTimeField;
            }
            set {
                this.preferredTimeField = value;
            }
        }
        
        /// <remarks/>
        public string PreferredWeekDay {
            get {
                return this.preferredWeekDayField;
            }
            set {
                this.preferredWeekDayField = value;
            }
        }
        
        /// <remarks/>
        public string VisitReason {
            get {
                return this.visitReasonField;
            }
            set {
                this.visitReasonField = value;
            }
        }
        
        /// <remarks/>
        public bool MessageUrgency {
            get {
                return this.messageUrgencyField;
            }
            set {
                this.messageUrgencyField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AppointmentStart {
            get {
                return this.appointmentStartField;
            }
            set {
                this.appointmentStartField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AppointmentEnd {
            get {
                return this.appointmentEndField;
            }
            set {
                this.appointmentEndField = value;
            }
        }
        
        /// <remarks/>
        public long ProviderId_Appointment {
            get {
                return this.providerId_AppointmentField;
            }
            set {
                this.providerId_AppointmentField = value;
            }
        }
        
        /// <remarks/>
        public string MedicationNDC {
            get {
                return this.medicationNDCField;
            }
            set {
                this.medicationNDCField = value;
            }
        }
        
        /// <remarks/>
        public string MedicationName {
            get {
                return this.medicationNameField;
            }
            set {
                this.medicationNameField = value;
            }
        }
        
        /// <remarks/>
        public int NoOfRefills {
            get {
                return this.noOfRefillsField;
            }
            set {
                this.noOfRefillsField = value;
            }
        }
        
        /// <remarks/>
        public int MedicationStatus {
            get {
                return this.medicationStatusField;
            }
            set {
                this.medicationStatusField = value;
            }
        }
        
        /// <remarks/>
        public string PharmacyName {
            get {
                return this.pharmacyNameField;
            }
            set {
                this.pharmacyNameField = value;
            }
        }
        
        /// <remarks/>
        public string PharmacyAddress {
            get {
                return this.pharmacyAddressField;
            }
            set {
                this.pharmacyAddressField = value;
            }
        }
        
        /// <remarks/>
        public string PharmacyPhone {
            get {
                return this.pharmacyPhoneField;
            }
            set {
                this.pharmacyPhoneField = value;
            }
        }
        
        /// <remarks/>
        public bool MessageRead {
            get {
                return this.messageReadField;
            }
            set {
                this.messageReadField = value;
            }
        }
        
        /// <remarks/>
        public string AttachmentId {
            get {
                return this.attachmentIdField;
            }
            set {
                this.attachmentIdField = value;
            }
        }
        
        /// <remarks/>
        public string AttachmentName {
            get {
                return this.attachmentNameField;
            }
            set {
                this.attachmentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable dtDetails {
            get {
                return this.dtDetailsField;
            }
            set {
                this.dtDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetMessageDataCompletedEventHandler(object sender, GetMessageDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void UpdateMessageReadFlagDataCompletedEventHandler(object sender, UpdateMessageReadFlagDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMessageReadFlagDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMessageReadFlagDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SaveMessageDataCompletedEventHandler(object sender, SaveMessageDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveMessageDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveMessageDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void CancelMessageCompletedEventHandler(object sender, CancelMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void DeleteMessageCompletedEventHandler(object sender, DeleteMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetMessageListCompletedEventHandler(object sender, GetMessageListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageTableData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageTableData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetMessageListProviderCompletedEventHandler(object sender, GetMessageListProviderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageListProviderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageListProviderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageTableData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageTableData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetMessageDetailSentListCompletedEventHandler(object sender, GetMessageDetailSentListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageDetailSentListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageDetailSentListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageTableData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageTableData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetMessageDetailReceivedListCompletedEventHandler(object sender, GetMessageDetailReceivedListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageDetailReceivedListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageDetailReceivedListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageTableData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageTableData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetMessageDetailProvSentListCompletedEventHandler(object sender, GetMessageDetailProvSentListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageDetailProvSentListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageDetailProvSentListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageTableData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageTableData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetMessageDetailProvReceivedListCompletedEventHandler(object sender, GetMessageDetailProvReceivedListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageDetailProvReceivedListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageDetailProvReceivedListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageTableData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageTableData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetMessageTypeCodesCompletedEventHandler(object sender, GetMessageTypeCodesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageTypeCodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageTypeCodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CodeTableData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CodeTableData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetMessageTypeGeneralCodesCompletedEventHandler(object sender, GetMessageTypeGeneralCodesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageTypeGeneralCodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageTypeGeneralCodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CodeTableData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CodeTableData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetMessageStatusCodesCompletedEventHandler(object sender, GetMessageStatusCodesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageStatusCodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageStatusCodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CodeTableData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CodeTableData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetMessageResponseTypeCodesCompletedEventHandler(object sender, GetMessageResponseTypeCodesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageResponseTypeCodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageResponseTypeCodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CodeTableData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CodeTableData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetMessagePeriodCodesCompletedEventHandler(object sender, GetMessagePeriodCodesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessagePeriodCodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessagePeriodCodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CodeTableData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CodeTableData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetMessageAttachmentDataCompletedEventHandler(object sender, GetMessageAttachmentDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageAttachmentDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageAttachmentDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageAttachmentData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageAttachmentData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetUnreadMessageDataCompletedEventHandler(object sender, GetUnreadMessageDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUnreadMessageDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUnreadMessageDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageUnread Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageUnread)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetUnreadProvMessageDataCompletedEventHandler(object sender, GetUnreadProvMessageDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUnreadProvMessageDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUnreadProvMessageDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessageUnread Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageUnread)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SendEmailMessageCompletedEventHandler(object sender, SendEmailMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendEmailMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendEmailMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmailMessageData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmailMessageData)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591